# Generated by Django 5.0.2 on 2024-03-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_video_is_1preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_1preview',
        ),
    ]
