# Generated by Django 3.1.14 on 2024-03-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20240331_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
