# Generated by Django 5.0.3 on 2024-04-02 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_course_id_alter_customuser_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='coursename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
