# Generated by Django 5.0.3 on 2024-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_demopay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('quiz_number', models.IntegerField()),
                ('quiz_link', models.URLField()),
            ],
        ),
    ]
